import type { Metadata } from "next";
import localFont from "next/font/local";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

// Fonts

export const worksans = localFont({
  src: [
    {
      path: "./assets/fonts/WorkSans/WorkSans-Regular.woff",
      weight:"400"
    },
    {
      path: "./assets/fonts/WorkSans/WorkSans-SemiBold.woff",
      weight:"600"
    },
  ],
    variable: "--font-worksans",

});

export const montserrat = localFont({
  src: "./assets/fonts/Montserrat/montserrat-v31-latin-900.woff2",
  variable: "--font-montserrat",
  weight: "900",
});

export const VCNudgeTrial = localFont({
  src: [
    {
      path: "./assets/fonts/VCNudgeTrial/VCNudgeBoldTrial.woff",
      weight: "700",
      style: "normal",
    },
    {
      path: "./assets/fonts/VCNudgeTrial/VCNudgeSemiBoldTrial.woff",
      weight: "600",
      style: "normal",
    },
    {
      path: "./assets/fonts/VCNudgeTrial/VCNudgeMediumTrial.woff",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-nudgetrial",
});

export const metadata: Metadata = {
  title: "Maximum Performance Health",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${montserrat.variable} ${VCNudgeTrial.variable} ${worksans.variable}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
